"""canonical_clean_baseline

Revision ID: 0001
Revises:
Create Date: 2026-07-15 08:09:35.703260
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage_daily',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('logical_operations', sa.Integer(), nullable=False),
    sa.Column('provider_attempts', sa.Integer(), nullable=False),
    sa.Column('cache_hits', sa.Integer(), nullable=False),
    sa.Column('billable_calls', sa.Integer(), nullable=False),
    sa.Column('unknown_billing_calls', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('day', 'provider')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('br_slug', sa.String(length=80), nullable=True),
    sa.Column('market', sa.String(length=20), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('shares_outstanding', sa.BigInteger(), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('enterprise_value', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=True)
    op.create_table('fetch_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('document_version_id', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fetch_log_document_version_id'), 'fetch_log', ['document_version_id'], unique=False)
    op.create_index('ix_fetch_log_url_at', 'fetch_log', ['url', 'fetched_at'], unique=False)
    op.create_table('list_poll_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=80), nullable=False),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scan_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scan_target_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scan_next_offset', sa.Integer(), nullable=True),
    sa.Column('scan_next_limit', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_list_poll_states_source_key'), 'list_poll_states', ['source_key'], unique=True)
    op.create_table('market_factor_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('page_document_versions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('parser_version', sa.String(length=40), nullable=False),
    sa.Column('coverage', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_factor_batches_as_of'), 'market_factor_batches', ['as_of'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_ref', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('base_currency', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_ref', name='uq_portfolio_provider_ref')
    )
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow', sa.String(length=80), nullable=False),
    sa.Column('trigger', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('model_role', sa.String(length=40), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('orchestrator_model', sa.String(length=80), nullable=True),
    sa.Column('idempotency_key', sa.String(length=160), nullable=True),
    sa.Column('inputs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('outputs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_owner', sa.String(length=160), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_available_at'), 'agent_runs', ['available_at'], unique=False)
    op.create_index(op.f('ix_agent_runs_idempotency_key'), 'agent_runs', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_agent_runs_lease_expires_at'), 'agent_runs', ['lease_expires_at'], unique=False)
    op.create_index(op.f('ix_agent_runs_lease_owner'), 'agent_runs', ['lease_owner'], unique=False)
    op.create_index('ix_agent_runs_status_created', 'agent_runs', ['status', 'created_at'], unique=False)
    op.create_index('ix_agent_runs_workflow_created', 'agent_runs', ['workflow', 'created_at'], unique=False)
    op.create_table('company_market_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('industry_type', sa.String(length=80), nullable=True),
    sa.Column('priority_values', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('forecast_consensus', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('advanced_metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('dividend_coverage', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    op.create_table('decision_journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('thesis', sa.Text(), nullable=False),
    sa.Column('invalidation', sa.Text(), nullable=False),
    sa.Column('next_check', sa.Text(), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('thesis_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('thesis_hash', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decision_journal_company_created', 'decision_journal_entries', ['company_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_decision_journal_entries_company_id'), 'decision_journal_entries', ['company_id'], unique=False)
    op.create_table('dividends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('dps', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('yield_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'year', name='uq_dividend_year')
    )
    op.create_table('event_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('raw_url', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('parsed', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('materiality', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_event_report_source_id')
    )
    op.create_index('ix_event_reports_company_published', 'event_reports', ['company_id', 'published_at'], unique=False)
    op.create_table('forum_intelligence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('industry_type', sa.String(length=80), nullable=True),
    sa.Column('last_30d_post_count', sa.Integer(), nullable=False),
    sa.Column('last_30d_active_user_count', sa.Integer(), nullable=False),
    sa.Column('activity_spikes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('community_sentiment', sa.String(length=30), nullable=True),
    sa.Column('distilled_facts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('expectations', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'source', name='uq_forum_intelligence_source')
    )
    op.create_table('indicator_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('indicator', sa.String(length=40), nullable=False),
    sa.Column('period', sa.String(length=8), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('source_fact_id', sa.Integer(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'indicator', 'period', name='uq_indicator_key')
    )
    op.create_index(op.f('ix_indicator_values_source_fact_id'), 'indicator_values', ['source_fact_id'], unique=False)
    op.create_table('instrument_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_key', sa.String(length=200), nullable=False),
    sa.Column('provider_ticker', sa.String(length=80), nullable=True),
    sa.Column('provider_name', sa.String(length=300), nullable=False),
    sa.Column('provider_type', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('mapping_kind', sa.String(length=20), nullable=False),
    sa.Column('mapping_status', sa.String(length=20), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_key', name='uq_instrument_mapping_provider_key')
    )
    op.create_index(op.f('ix_instrument_mappings_company_id'), 'instrument_mappings', ['company_id'], unique=False)
    op.create_table('market_factor_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('br_slug', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('report_period', sa.String(length=20), nullable=True),
    sa.Column('altman_grade', sa.String(length=8), nullable=True),
    sa.Column('altman_value', sa.Float(), nullable=True),
    sa.Column('piotroski_f', sa.Float(), nullable=True),
    sa.Column('cz', sa.Float(), nullable=True),
    sa.Column('cz_delta_rr_pct', sa.Float(), nullable=True),
    sa.Column('cwk', sa.Float(), nullable=True),
    sa.Column('ev_ebitda', sa.Float(), nullable=True),
    sa.Column('roe_pct', sa.Float(), nullable=True),
    sa.Column('op_margin_pct', sa.Float(), nullable=True),
    sa.Column('op_margin_delta_pp', sa.Float(), nullable=True),
    sa.Column('net_margin_pct', sa.Float(), nullable=True),
    sa.Column('revenue_dyn_rr_pct', sa.Float(), nullable=True),
    sa.Column('net_income_dyn_rr_pct', sa.Float(), nullable=True),
    sa.Column('debt_to_equity', sa.Float(), nullable=True),
    sa.Column('net_debt_ebitda', sa.Float(), nullable=True),
    sa.Column('net_income_ttm_pln_thousands', sa.Float(), nullable=True),
    sa.Column('equity_pln_thousands', sa.Float(), nullable=True),
    sa.Column('turnover_present', sa.Boolean(), nullable=True),
    sa.Column('extras', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['market_factor_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'ticker', name='uq_market_factor_row_batch_ticker')
    )
    op.create_index(op.f('ix_market_factor_rows_batch_id'), 'market_factor_rows', ['batch_id'], unique=False)
    op.create_index('ix_market_factor_rows_batch_ticker', 'market_factor_rows', ['batch_id', 'ticker'], unique=False)
    op.create_index(op.f('ix_market_factor_rows_ticker'), 'market_factor_rows', ['ticker'], unique=False)
    op.create_table('portfolio_operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('instrument_name', sa.String(length=240), nullable=True),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('amount_pln', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('provider_key', sa.String(length=120), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'content_hash', name='uq_portfolio_operation_content')
    )
    op.create_index(op.f('ix_portfolio_operations_kind'), 'portfolio_operations', ['kind'], unique=False)
    op.create_index('ix_portfolio_operations_portfolio_date', 'portfolio_operations', ['portfolio_id', 'occurred_on'], unique=False)
    op.create_index(op.f('ix_portfolio_operations_portfolio_id'), 'portfolio_operations', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_portfolio_operations_ticker'), 'portfolio_operations', ['ticker'], unique=False)
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('cost_basis', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('profit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('cash_value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('benchmark_name', sa.String(length=160), nullable=True),
    sa.Column('input_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('gaps', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('version > 0', name='ck_portfolio_snapshot_positive_version'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'version', name='uq_portfolio_snapshot_version')
    )
    op.create_index(op.f('ix_portfolio_snapshots_as_of'), 'portfolio_snapshots', ['as_of'], unique=False)
    op.create_index(op.f('ix_portfolio_snapshots_input_fingerprint'), 'portfolio_snapshots', ['input_fingerprint'], unique=False)
    op.create_index('ix_portfolio_snapshots_portfolio_as_of', 'portfolio_snapshots', ['portfolio_id', 'as_of'], unique=False)
    op.create_index(op.f('ix_portfolio_snapshots_portfolio_id'), 'portfolio_snapshots', ['portfolio_id'], unique=False)
    op.create_table('report_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('statement', sa.String(length=10), nullable=False),
    sa.Column('freq', sa.String(length=1), nullable=False),
    sa.Column('period', sa.String(length=8), nullable=False),
    sa.Column('field_code', sa.String(length=80), nullable=False),
    sa.Column('field_label', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('source_fact_id', sa.Integer(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'statement', 'freq', 'period', 'field_code', name='uq_report_value_key')
    )
    op.create_index('ix_report_values_lookup', 'report_values', ['company_id', 'statement', 'freq'], unique=False)
    op.create_index(op.f('ix_report_values_source_fact_id'), 'report_values', ['source_fact_id'], unique=False)
    op.create_table('research_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=80), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('current_step', sa.String(length=40), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'purpose', name='uq_research_case_company_purpose')
    )
    op.create_index(op.f('ix_research_cases_company_id'), 'research_cases', ['company_id'], unique=False)
    op.create_index(op.f('ix_research_cases_state'), 'research_cases', ['state'], unique=False)
    op.create_table('source_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('company_ticker', sa.String(length=12), nullable=False),
    sa.Column('source_name', sa.String(length=80), nullable=False),
    sa.Column('source_type', sa.String(length=80), nullable=False),
    sa.Column('scope_key', sa.String(length=200), nullable=False),
    sa.Column('canonical_url', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('period', sa.String(length=40), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latest_content_hash', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('parser_version', sa.String(length=120), nullable=False),
    sa.Column('last_fetch_status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_ticker', 'source_name', 'source_type', 'scope_key', name='uq_source_document_identity')
    )
    op.create_index(op.f('ix_source_documents_company_id'), 'source_documents', ['company_id'], unique=False)
    op.create_index(op.f('ix_source_documents_company_ticker'), 'source_documents', ['company_ticker'], unique=False)
    op.create_index(op.f('ix_source_documents_source_type'), 'source_documents', ['source_type'], unique=False)
    op.create_table('thesis_falsifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('thesis_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'key', name='uq_thesis_falsifier_company_key')
    )
    op.create_index(op.f('ix_thesis_falsifiers_company_id'), 'thesis_falsifiers', ['company_id'], unique=False)
    op.create_index('ix_thesis_falsifiers_company_status', 'thesis_falsifiers', ['company_id', 'status'], unique=False)
    op.create_index(op.f('ix_thesis_falsifiers_status'), 'thesis_falsifiers', ['status'], unique=False)
    op.create_table('company_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('research_case_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.String(length=40), nullable=False),
    sa.Column('archetype', sa.String(length=40), nullable=False),
    sa.Column('archetype_version', sa.String(length=40), nullable=False),
    sa.Column('company_overlay', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('drivers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('kpis', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('provenance', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=True),
    sa.Column('based_on_profile_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('version > 0', name='ck_company_profile_positive_version'),
    sa.ForeignKeyConstraint(['based_on_profile_id'], ['company_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['research_case_id'], ['research_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('research_case_id', 'version', name='uq_company_profile_case_version')
    )
    op.create_index(op.f('ix_company_profiles_archetype'), 'company_profiles', ['archetype'], unique=False)
    op.create_index(op.f('ix_company_profiles_based_on_profile_id'), 'company_profiles', ['based_on_profile_id'], unique=False)
    op.create_index(op.f('ix_company_profiles_research_case_id'), 'company_profiles', ['research_case_id'], unique=False)
    op.create_table('document_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('requested_url', sa.String(length=1000), nullable=False),
    sa.Column('effective_url', sa.String(length=1000), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('parser_version', sa.String(length=120), nullable=False),
    sa.Column('parse_status', sa.String(length=40), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_document_id', 'content_hash', name='uq_document_version_hash')
    )
    op.create_index(op.f('ix_document_versions_source_document_id'), 'document_versions', ['source_document_id'], unique=False)
    op.create_table('portfolio_position_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('mapping_id', sa.Integer(), nullable=False),
    sa.Column('mapping_kind', sa.String(length=20), nullable=False),
    sa.Column('mapping_status', sa.String(length=20), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('provider_row_key', sa.String(length=200), nullable=False),
    sa.Column('ticker', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('asset_type', sa.String(length=100), nullable=True),
    sa.Column('sector', sa.String(length=160), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('quote_date', sa.Date(), nullable=True),
    sa.Column('quote', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('value', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('cost_basis', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('profit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('allocation_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mapping_id'], ['instrument_mappings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['portfolio_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'provider_row_key', name='uq_portfolio_position_row')
    )
    op.create_index(op.f('ix_portfolio_position_snapshots_company_id'), 'portfolio_position_snapshots', ['company_id'], unique=False)
    op.create_index(op.f('ix_portfolio_position_snapshots_mapping_id'), 'portfolio_position_snapshots', ['mapping_id'], unique=False)
    op.create_index(op.f('ix_portfolio_position_snapshots_snapshot_id'), 'portfolio_position_snapshots', ['snapshot_id'], unique=False)
    op.create_table('portfolio_syncs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('provider_status_code', sa.String(length=30), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('parser_version', sa.String(length=40), nullable=False),
    sa.Column('reused_snapshot', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['portfolio_snapshots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_syncs_payload_hash'), 'portfolio_syncs', ['payload_hash'], unique=False)
    op.create_index(op.f('ix_portfolio_syncs_portfolio_id'), 'portfolio_syncs', ['portfolio_id'], unique=False)
    op.create_index('ix_portfolio_syncs_portfolio_requested', 'portfolio_syncs', ['portfolio_id', 'requested_at'], unique=False)
    op.create_index(op.f('ix_portfolio_syncs_snapshot_id'), 'portfolio_syncs', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_portfolio_syncs_status'), 'portfolio_syncs', ['status'], unique=False)
    op.create_table('portfolio_value_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('contributed', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('profit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('provider_return_pct', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('benchmark_return_pct', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('daily_change', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['portfolio_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'date', name='uq_portfolio_value_point_date')
    )
    op.create_index(op.f('ix_portfolio_value_points_snapshot_id'), 'portfolio_value_points', ['snapshot_id'], unique=False)
    op.create_table('research_case_step_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('research_case_id', sa.Integer(), nullable=False),
    sa.Column('from_state', sa.String(length=40), nullable=True),
    sa.Column('from_step', sa.String(length=40), nullable=True),
    sa.Column('to_state', sa.String(length=40), nullable=False),
    sa.Column('to_step', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('changed_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['research_case_id'], ['research_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_case_step_history_case_created', 'research_case_step_history', ['research_case_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_research_case_step_history_research_case_id'), 'research_case_step_history', ['research_case_id'], unique=False)
    op.create_table('verification_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_run_id', sa.Integer(), nullable=True),
    sa.Column('model_role', sa.String(length=40), nullable=False),
    sa.Column('verifier_model', sa.String(length=80), nullable=False),
    sa.Column('verdict', sa.String(length=30), nullable=False),
    sa.Column('checks', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_verification_runs_agent_created', 'verification_runs', ['agent_run_id', 'created_at'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('company_ticker', sa.String(length=12), nullable=False),
    sa.Column('source_version_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('known_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('claims', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('verification_state', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_company_id'), 'events', ['company_id'], unique=False)
    op.create_index(op.f('ix_events_company_ticker'), 'events', ['company_ticker'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_known_at'), 'events', ['known_at'], unique=False)
    op.create_index(op.f('ix_events_source_version_id'), 'events', ['source_version_id'], unique=False)
    op.create_table('facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('company_ticker', sa.String(length=12), nullable=False),
    sa.Column('source_version_id', sa.Integer(), nullable=False),
    sa.Column('fact_type', sa.String(length=80), nullable=False),
    sa.Column('fact_key', sa.String(length=200), nullable=False),
    sa.Column('fact_hash', sa.String(length=64), nullable=False),
    sa.Column('numeric_value', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=80), nullable=True),
    sa.Column('period', sa.String(length=40), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('known_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locator', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('extractor_version', sa.String(length=120), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('verification_state', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_version_id', 'fact_hash', name='uq_fact_version_hash')
    )
    op.create_index(op.f('ix_facts_company_id'), 'facts', ['company_id'], unique=False)
    op.create_index('ix_facts_company_known_key', 'facts', ['company_id', 'known_at', 'fact_key'], unique=False)
    op.create_index(op.f('ix_facts_company_ticker'), 'facts', ['company_ticker'], unique=False)
    op.create_index(op.f('ix_facts_known_at'), 'facts', ['known_at'], unique=False)
    op.create_index(op.f('ix_facts_source_version_id'), 'facts', ['source_version_id'], unique=False)
    op.create_index(op.f('ix_facts_verification_state'), 'facts', ['verification_state'], unique=False)
    op.create_table('portfolio_review_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('agent_run_id', sa.Integer(), nullable=False),
    sa.Column('verification_run_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('contract_version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('draft_requested_model_role', sa.String(length=40), nullable=False),
    sa.Column('draft_requested_model', sa.String(length=80), nullable=False),
    sa.Column('draft_reasoning_effort', sa.String(length=20), nullable=False),
    sa.Column('draft_actual_host_model', sa.String(length=160), nullable=False),
    sa.Column('draft_substitution_or_escalation', sa.String(length=1000), nullable=True),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sections', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('input_manifest', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('gaps', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('input_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('analytics_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('draft_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('artifact_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('verifier_result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('provisional', 'verified', 'rejected', 'needs-human')", name='ck_portfolio_review_status'),
    sa.CheckConstraint('version > 0', name='ck_portfolio_review_positive_version'),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portfolio_snapshot_id'], ['portfolio_snapshots.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verification_run_id'], ['verification_runs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_run_id', name='uq_portfolio_review_agent_run'),
    sa.UniqueConstraint('portfolio_id', 'version', name='uq_portfolio_review_version'),
    sa.UniqueConstraint('verification_run_id', name='uq_portfolio_review_verification_run')
    )
    op.create_index('ix_portfolio_review_portfolio_created', 'portfolio_review_snapshots', ['portfolio_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_portfolio_review_snapshots_agent_run_id'), 'portfolio_review_snapshots', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_portfolio_review_snapshots_as_of'), 'portfolio_review_snapshots', ['as_of'], unique=False)
    op.create_index(op.f('ix_portfolio_review_snapshots_portfolio_id'), 'portfolio_review_snapshots', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_portfolio_review_snapshots_portfolio_snapshot_id'), 'portfolio_review_snapshots', ['portfolio_snapshot_id'], unique=False)
    op.create_index(op.f('ix_portfolio_review_snapshots_status'), 'portfolio_review_snapshots', ['status'], unique=False)
    op.create_index(op.f('ix_portfolio_review_snapshots_verification_run_id'), 'portfolio_review_snapshots', ['verification_run_id'], unique=False)
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('source_version_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('close', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('source_name', sa.String(length=80), nullable=True),
    sa.Column('series_key', sa.String(length=160), nullable=True),
    sa.Column('basis_version', sa.String(length=80), nullable=True),
    sa.Column('adjustment_status', sa.String(length=40), server_default='unknown', nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("adjustment_status IN ('unknown', 'raw_unverified', 'split_adjusted', 'total_return')", name='ck_prices_adjustment_status'),
    sa.CheckConstraint("adjustment_status NOT IN ('split_adjusted', 'total_return') OR (source_name IS NOT NULL AND length(trim(source_name)) > 0 AND series_key IS NOT NULL AND length(trim(series_key)) > 0 AND basis_version IS NOT NULL AND length(trim(basis_version)) > 0)", name='ck_prices_eligible_provenance'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_version_id'], ['document_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'date', name='uq_price_day')
    )
    op.create_index(op.f('ix_prices_adjustment_status'), 'prices', ['adjustment_status'], unique=False)
    op.create_index(op.f('ix_prices_scraped_at'), 'prices', ['scraped_at'], unique=False)
    op.create_index(op.f('ix_prices_series_key'), 'prices', ['series_key'], unique=False)
    op.create_index(op.f('ix_prices_source_version_id'), 'prices', ['source_version_id'], unique=False)
    op.create_table('research_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('research_case_id', sa.Integer(), nullable=False),
    sa.Column('company_profile_id', sa.Integer(), nullable=False),
    sa.Column('agent_run_id', sa.Integer(), nullable=False),
    sa.Column('verification_run_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('contract_version', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('input_fingerprint', sa.String(length=128), nullable=False),
    sa.Column('artifact_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('sections', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source_manifest', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('conflicts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('gaps', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('next_checks', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('statement_provenance', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('verifier_result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('provisional', 'verified', 'rejected', 'needs-human')", name='ck_research_snapshot_status'),
    sa.CheckConstraint('version > 0', name='ck_research_snapshot_positive_version'),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_profile_id'], ['company_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['research_case_id'], ['research_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verification_run_id'], ['verification_runs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_run_id', name='uq_research_snapshot_agent_run'),
    sa.UniqueConstraint('research_case_id', 'version', name='uq_research_snapshot_case_version'),
    sa.UniqueConstraint('verification_run_id', name='uq_research_snapshot_verification_run')
    )
    op.create_index(op.f('ix_research_snapshots_agent_run_id'), 'research_snapshots', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_research_snapshots_as_of'), 'research_snapshots', ['as_of'], unique=False)
    op.create_index('ix_research_snapshots_case_created', 'research_snapshots', ['research_case_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_research_snapshots_company_profile_id'), 'research_snapshots', ['company_profile_id'], unique=False)
    op.create_index(op.f('ix_research_snapshots_research_case_id'), 'research_snapshots', ['research_case_id'], unique=False)
    op.create_index(op.f('ix_research_snapshots_status'), 'research_snapshots', ['status'], unique=False)
    op.create_index(op.f('ix_research_snapshots_verification_run_id'), 'research_snapshots', ['verification_run_id'], unique=False)
    op.create_table('data_conflicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('company_ticker', sa.String(length=12), nullable=False),
    sa.Column('fact_key', sa.String(length=200), nullable=False),
    sa.Column('period', sa.String(length=40), nullable=True),
    sa.Column('left_fact_id', sa.Integer(), nullable=False),
    sa.Column('right_fact_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('resolution_rule', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['left_fact_id'], ['facts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['right_fact_id'], ['facts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('left_fact_id', 'right_fact_id', name='uq_data_conflict_fact_pair')
    )
    op.create_index(op.f('ix_data_conflicts_company_id'), 'data_conflicts', ['company_id'], unique=False)
    op.create_index(op.f('ix_data_conflicts_company_ticker'), 'data_conflicts', ['company_ticker'], unique=False)
    op.create_index(op.f('ix_data_conflicts_fact_key'), 'data_conflicts', ['fact_key'], unique=False)
    op.create_index(op.f('ix_data_conflicts_status'), 'data_conflicts', ['status'], unique=False)
    op.create_table('valuation_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('research_case_id', sa.Integer(), nullable=False),
    sa.Column('research_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('agent_run_id', sa.Integer(), nullable=True),
    sa.Column('verification_run_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('contract_version', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('template_id', sa.String(length=80), nullable=False),
    sa.Column('template_version', sa.String(length=60), nullable=False),
    sa.Column('calculation_engine_version', sa.String(length=60), nullable=False),
    sa.Column('assumptions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('base_values', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('deterministic_outputs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('codex_judgment', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('input_manifest', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('gaps', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('input_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('calculation_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('artifact_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('verifier_result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('provisional', 'verified', 'rejected', 'needs-human')", name='ck_valuation_snapshot_status'),
    sa.CheckConstraint('version > 0', name='ck_valuation_snapshot_positive_version'),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['research_case_id'], ['research_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['research_snapshot_id'], ['research_snapshots.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verification_run_id'], ['verification_runs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_run_id', name='uq_valuation_snapshot_agent_run'),
    sa.UniqueConstraint('research_case_id', 'version', name='uq_valuation_snapshot_case_version'),
    sa.UniqueConstraint('verification_run_id', name='uq_valuation_snapshot_verification_run')
    )
    op.create_index(op.f('ix_valuation_snapshots_agent_run_id'), 'valuation_snapshots', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_valuation_snapshots_as_of'), 'valuation_snapshots', ['as_of'], unique=False)
    op.create_index('ix_valuation_snapshots_case_created', 'valuation_snapshots', ['research_case_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_valuation_snapshots_research_case_id'), 'valuation_snapshots', ['research_case_id'], unique=False)
    op.create_index(op.f('ix_valuation_snapshots_research_snapshot_id'), 'valuation_snapshots', ['research_snapshot_id'], unique=False)
    op.create_index(op.f('ix_valuation_snapshots_status'), 'valuation_snapshots', ['status'], unique=False)
    op.create_index(op.f('ix_valuation_snapshots_verification_run_id'), 'valuation_snapshots', ['verification_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_valuation_snapshots_verification_run_id'), table_name='valuation_snapshots')
    op.drop_index(op.f('ix_valuation_snapshots_status'), table_name='valuation_snapshots')
    op.drop_index(op.f('ix_valuation_snapshots_research_snapshot_id'), table_name='valuation_snapshots')
    op.drop_index(op.f('ix_valuation_snapshots_research_case_id'), table_name='valuation_snapshots')
    op.drop_index('ix_valuation_snapshots_case_created', table_name='valuation_snapshots')
    op.drop_index(op.f('ix_valuation_snapshots_as_of'), table_name='valuation_snapshots')
    op.drop_index(op.f('ix_valuation_snapshots_agent_run_id'), table_name='valuation_snapshots')
    op.drop_table('valuation_snapshots')
    op.drop_index(op.f('ix_data_conflicts_status'), table_name='data_conflicts')
    op.drop_index(op.f('ix_data_conflicts_fact_key'), table_name='data_conflicts')
    op.drop_index(op.f('ix_data_conflicts_company_ticker'), table_name='data_conflicts')
    op.drop_index(op.f('ix_data_conflicts_company_id'), table_name='data_conflicts')
    op.drop_table('data_conflicts')
    op.drop_index(op.f('ix_research_snapshots_verification_run_id'), table_name='research_snapshots')
    op.drop_index(op.f('ix_research_snapshots_status'), table_name='research_snapshots')
    op.drop_index(op.f('ix_research_snapshots_research_case_id'), table_name='research_snapshots')
    op.drop_index(op.f('ix_research_snapshots_company_profile_id'), table_name='research_snapshots')
    op.drop_index('ix_research_snapshots_case_created', table_name='research_snapshots')
    op.drop_index(op.f('ix_research_snapshots_as_of'), table_name='research_snapshots')
    op.drop_index(op.f('ix_research_snapshots_agent_run_id'), table_name='research_snapshots')
    op.drop_table('research_snapshots')
    op.drop_index(op.f('ix_prices_source_version_id'), table_name='prices')
    op.drop_index(op.f('ix_prices_series_key'), table_name='prices')
    op.drop_index(op.f('ix_prices_scraped_at'), table_name='prices')
    op.drop_index(op.f('ix_prices_adjustment_status'), table_name='prices')
    op.drop_table('prices')
    op.drop_index(op.f('ix_portfolio_review_snapshots_verification_run_id'), table_name='portfolio_review_snapshots')
    op.drop_index(op.f('ix_portfolio_review_snapshots_status'), table_name='portfolio_review_snapshots')
    op.drop_index(op.f('ix_portfolio_review_snapshots_portfolio_snapshot_id'), table_name='portfolio_review_snapshots')
    op.drop_index(op.f('ix_portfolio_review_snapshots_portfolio_id'), table_name='portfolio_review_snapshots')
    op.drop_index(op.f('ix_portfolio_review_snapshots_as_of'), table_name='portfolio_review_snapshots')
    op.drop_index(op.f('ix_portfolio_review_snapshots_agent_run_id'), table_name='portfolio_review_snapshots')
    op.drop_index('ix_portfolio_review_portfolio_created', table_name='portfolio_review_snapshots')
    op.drop_table('portfolio_review_snapshots')
    op.drop_index(op.f('ix_facts_verification_state'), table_name='facts')
    op.drop_index(op.f('ix_facts_source_version_id'), table_name='facts')
    op.drop_index(op.f('ix_facts_known_at'), table_name='facts')
    op.drop_index(op.f('ix_facts_company_ticker'), table_name='facts')
    op.drop_index('ix_facts_company_known_key', table_name='facts')
    op.drop_index(op.f('ix_facts_company_id'), table_name='facts')
    op.drop_table('facts')
    op.drop_index(op.f('ix_events_source_version_id'), table_name='events')
    op.drop_index(op.f('ix_events_known_at'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_company_ticker'), table_name='events')
    op.drop_index(op.f('ix_events_company_id'), table_name='events')
    op.drop_table('events')
    op.drop_index('ix_verification_runs_agent_created', table_name='verification_runs')
    op.drop_table('verification_runs')
    op.drop_index(op.f('ix_research_case_step_history_research_case_id'), table_name='research_case_step_history')
    op.drop_index('ix_case_step_history_case_created', table_name='research_case_step_history')
    op.drop_table('research_case_step_history')
    op.drop_index(op.f('ix_portfolio_value_points_snapshot_id'), table_name='portfolio_value_points')
    op.drop_table('portfolio_value_points')
    op.drop_index(op.f('ix_portfolio_syncs_status'), table_name='portfolio_syncs')
    op.drop_index(op.f('ix_portfolio_syncs_snapshot_id'), table_name='portfolio_syncs')
    op.drop_index('ix_portfolio_syncs_portfolio_requested', table_name='portfolio_syncs')
    op.drop_index(op.f('ix_portfolio_syncs_portfolio_id'), table_name='portfolio_syncs')
    op.drop_index(op.f('ix_portfolio_syncs_payload_hash'), table_name='portfolio_syncs')
    op.drop_table('portfolio_syncs')
    op.drop_index(op.f('ix_portfolio_position_snapshots_snapshot_id'), table_name='portfolio_position_snapshots')
    op.drop_index(op.f('ix_portfolio_position_snapshots_mapping_id'), table_name='portfolio_position_snapshots')
    op.drop_index(op.f('ix_portfolio_position_snapshots_company_id'), table_name='portfolio_position_snapshots')
    op.drop_table('portfolio_position_snapshots')
    op.drop_index(op.f('ix_document_versions_source_document_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_company_profiles_research_case_id'), table_name='company_profiles')
    op.drop_index(op.f('ix_company_profiles_based_on_profile_id'), table_name='company_profiles')
    op.drop_index(op.f('ix_company_profiles_archetype'), table_name='company_profiles')
    op.drop_table('company_profiles')
    op.drop_index(op.f('ix_thesis_falsifiers_status'), table_name='thesis_falsifiers')
    op.drop_index('ix_thesis_falsifiers_company_status', table_name='thesis_falsifiers')
    op.drop_index(op.f('ix_thesis_falsifiers_company_id'), table_name='thesis_falsifiers')
    op.drop_table('thesis_falsifiers')
    op.drop_index(op.f('ix_source_documents_source_type'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_company_ticker'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_company_id'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index(op.f('ix_research_cases_state'), table_name='research_cases')
    op.drop_index(op.f('ix_research_cases_company_id'), table_name='research_cases')
    op.drop_table('research_cases')
    op.drop_index(op.f('ix_report_values_source_fact_id'), table_name='report_values')
    op.drop_index('ix_report_values_lookup', table_name='report_values')
    op.drop_table('report_values')
    op.drop_index(op.f('ix_portfolio_snapshots_portfolio_id'), table_name='portfolio_snapshots')
    op.drop_index('ix_portfolio_snapshots_portfolio_as_of', table_name='portfolio_snapshots')
    op.drop_index(op.f('ix_portfolio_snapshots_input_fingerprint'), table_name='portfolio_snapshots')
    op.drop_index(op.f('ix_portfolio_snapshots_as_of'), table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_index(op.f('ix_portfolio_operations_ticker'), table_name='portfolio_operations')
    op.drop_index(op.f('ix_portfolio_operations_portfolio_id'), table_name='portfolio_operations')
    op.drop_index('ix_portfolio_operations_portfolio_date', table_name='portfolio_operations')
    op.drop_index(op.f('ix_portfolio_operations_kind'), table_name='portfolio_operations')
    op.drop_table('portfolio_operations')
    op.drop_index(op.f('ix_market_factor_rows_ticker'), table_name='market_factor_rows')
    op.drop_index('ix_market_factor_rows_batch_ticker', table_name='market_factor_rows')
    op.drop_index(op.f('ix_market_factor_rows_batch_id'), table_name='market_factor_rows')
    op.drop_table('market_factor_rows')
    op.drop_index(op.f('ix_instrument_mappings_company_id'), table_name='instrument_mappings')
    op.drop_table('instrument_mappings')
    op.drop_index(op.f('ix_indicator_values_source_fact_id'), table_name='indicator_values')
    op.drop_table('indicator_values')
    op.drop_table('forum_intelligence')
    op.drop_index('ix_event_reports_company_published', table_name='event_reports')
    op.drop_table('event_reports')
    op.drop_table('dividends')
    op.drop_index(op.f('ix_decision_journal_entries_company_id'), table_name='decision_journal_entries')
    op.drop_index('ix_decision_journal_company_created', table_name='decision_journal_entries')
    op.drop_table('decision_journal_entries')
    op.drop_table('company_market_data')
    op.drop_index('ix_agent_runs_workflow_created', table_name='agent_runs')
    op.drop_index('ix_agent_runs_status_created', table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_lease_owner'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_lease_expires_at'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_idempotency_key'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_available_at'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_market_factor_batches_as_of'), table_name='market_factor_batches')
    op.drop_table('market_factor_batches')
    op.drop_index(op.f('ix_list_poll_states_source_key'), table_name='list_poll_states')
    op.drop_table('list_poll_states')
    op.drop_index('ix_fetch_log_url_at', table_name='fetch_log')
    op.drop_index(op.f('ix_fetch_log_document_version_id'), table_name='fetch_log')
    op.drop_table('fetch_log')
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_table('companies')
    op.drop_table('ai_usage_daily')
    # ### end Alembic commands ###
